/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mci.url.sniffer;

public class App {

    public static void main(String[] args) {
        HttpServer.getInstance().runServer();
        KSQKProducer.getInstance();
    }
}
